# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    # ✅ Cert, Sigh 방식으로 인증할 때 사용하는 인증 함수다.
    # get_certificates로 인증서를, get_provisioning_profile로 프로필을 가져온다.
    get_certificates
    get_provisioning_profile

    # ✅ 자동으로 빌드 넘버를 증가
    increment_build_number(xcodeproj: "orange-stock-ios.xcodeproj")

    # ✅ 빌드할 워크스페이스와 빌드 스키마 지정
    build_app(workspace: "orange-stock-ios.xcworkspace", scheme: "orange-stock-ios")

    upload_to_testflight
  end
end
