# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'orange-stock-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for orange-stock-ios

  target 'orange-stock-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'orange-stock-iosUITests' do
    # Pods for testing
  end


pod 'Moya', '~> 15.0'

end
